### ISSUE TITLE
TypeError: Interfaces cannot inherit. interface AggregatorV2V3Interface is AggregatorInterface, AggregatorV3Interface

### ISSUE THREAD

**Issue by themodfunction** [PatrickAlphaC/brownie_fund_me#14]
I keep getting this error when i try to compile. I tried shifting versions, but to no use. Please help thanks

**Comment by themodfunction** [comment]
Hey Guys! 
I found a solution to remove V2V3 and just put V3. 
It works.

**Comment by FCardellino** [comment]
Hello! Can you indicate where or how you remove V2V3? Thanks!

**Comment by themodfunction** [comment]
Hey @FCardellino 
In almost all places where V2V3 occurs, replace it by just V3

**Comment by Simposter45** [comment]
I was having the same problem and was stuck for over 4 hours with this. I was using `pragma solidity ^0.8.0;` solidity version and compiling on 0.6.0 version. There are some serious problems with the Aggregators to be honest. 

Finally, somehow I found a way to compile the MockV3Aggregator as well......

Just use:

```
 - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
 - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
```

Both of these in the Config file....and then you're good to go!

HOPE IT HELPS. 
**Thanks.**

**Comment by PatrickAlphaC** [comment]
That's really odd.... 

The `0.2.1` should do the trick...

**Comment by JCDC9919** [comment]
I got it to compile in the end, but couldn't get the red warning for my `import "@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol";` line to go away!

**Comment by cryptony8055** [comment]
im having this same issue . cant get the mockV3Aggregator to compile . cant get past that section bc of the issue

**Comment by FCardellino** [comment]
Hi @cryptony8055, I solved the issue in this [way ](https://github.com/PatrickAlphaC/brownie_fund_me/issues/13). I hope it can help you!

**Comment by JCDC9919** [comment]
Hi @cryptony8055, I'm not sure if it's the "correct way" but I found it seemed to work if you widen the scope of the Solidity versions:
`pragma solidity >=0.6.0 <0.9.0;`
Using the carrot notation on 0.6.0 seemed to give me further errors 
This was using 0.3.0 chainlink in the .config file

**Comment by cryptony8055** [comment]
hey @JCDC9919  thanks a lot it woked .

**Comment by PatrickAlphaC** [comment]
Closing, feel free to open back up.
