### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by pushpender-singh** [PatrickAlphaC/brownie_fund_me#17]
I am following the FREECODECAMP Solidity, Blockchain, and Smart Contract Course and got struck at 5:42:00. getting this error IndexError: list index out of range. 
I am unable to find how it can be solved.
 
attaching a screenshot of the error.
![Screenshot (960)](https://user-images.githubusercontent.com/59024943/147902831-99d9d319-6242-430b-a7e4-e935cf60e81c.png)

**Comment by MFCardozo** [comment]
Hope this help you! [https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions/687](url)
