### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by HarveyUdon** [PatrickAlphaC/brownie_fund_me#18]
I'm getting this error when I input "brownie run scripts/deploy.py"

**Comment by HarveyUdon** [comment]
never found why it was throwing that error, I just threw out the whole deploy.py and copy/pasted the one off of here, still get the same error. I'm going to try replacing all the files with the provided files

**Comment by PatrickAlphaC** [comment]
So, you're all set?

**Comment by PatrickAlphaC** [comment]
Closing, feel free to follow up
