### ISSUE TITLE
TypeError: 'ContractContainer' object is not callable

### ISSUE THREAD

**Issue by TiagoBlauth** [PatrickAlphaC/brownie_fund_me#20]
Hi smart ones..... 

I can deploy FundMe at rinkeby, but I am facing issues to deploy it at local ganache. The error happens at this command

        mock_aggregator = MockV3Aggregator(18, 200000000000000000000, {"from": account})

![image](https://user-images.githubusercontent.com/97102428/148790731-1c8aa60c-beba-4e51-94cf-c5f67c645d4b.png)

Many thanks in advance.

**Comment by PatrickAlphaC** [comment]
Change the line to:
```
MockV3Aggregator.deploy(DECIMALS, STARTING_PRICE, {"from": get_account()})
```
