### ISSUE TITLE
Error in brownie test

### ISSUE THREAD

**Issue by Simposter45** [PatrickAlphaC/brownie_fund_me#23]
As explained by Patrick, we need to close the Ganache-UI before writing `brownie test` in the terminal.
So did I keeping everything same.....and got a massive error for some reason where the main error message was: 
`ValueError: sender doesn't have enough funds to send tx. The upfront cost is: 25000000000000000 and the sender's account only has: 0`

**Error screen part 1:**
![image](https://user-images.githubusercontent.com/98341339/151011968-51bfa606-b927-4112-82d2-651503a308ea.png)
**Error screen part 2:**
![image](https://user-images.githubusercontent.com/98341339/151012212-b5bf08fa-2086-4e55-911b-dd55d8deae24.png)

My `test_fund_me.py` code (until now) looks like this:

```
from scripts.helpful_scripts import get_account
from scripts.deploy import deploy_fund_me
import pytest


def test_fund_and_withdraw():
    account = get_account()
    fund_me = deploy_fund_me()
    entrance_fee = fund_me.getEntranceFee()
    tx1 = fund_me.fund({"from": account, "value": entrance_fee})
    tx1.wait(1)
    assert fund_me.addressToAmountFunded(account.address) == entrance_fee
    tx2 = fund_me.withdraw({"from": account})
    tx2.wait(1)
    assert fund_me.addressToAmountFunded(account.address) == 0
```

I'm a complete newbie in this field and thus have very limited knowledge about it. 

_Thanks in advance_

**Comment by Simposter45** [comment]
> As explained by Patrick, we need to close the Ganache-UI before writing `brownie test` in the terminal. So did I keeping everything same.....and got a massive error for some reason where the main error message was: `ValueError: sender doesn't have enough funds to send tx. The upfront cost is: 25000000000000000 and the sender's account only has: 0`
> 
> **Error screen part 1:** ![image](https://user-images.githubusercontent.com/98341339/151011968-51bfa606-b927-4112-82d2-651503a308ea.png) **Error screen part 2:** ![image](https://user-images.githubusercontent.com/98341339/151012212-b5bf08fa-2086-4e55-911b-dd55d8deae24.png)
> 
> My `test_fund_me.py` code (until now) looks like this:
> 
> ```
> from scripts.helpful_scripts import get_account
> from scripts.deploy import deploy_fund_me
> import pytest
> 
> 
> def test_fund_and_withdraw():
>     account = get_account()
>     fund_me = deploy_fund_me()
>     entrance_fee = fund_me.getEntranceFee()
>     tx1 = fund_me.fund({"from": account, "value": entrance_fee})
>     tx1.wait(1)
>     assert fund_me.addressToAmountFunded(account.address) == entrance_fee
>     tx2 = fund_me.withdraw({"from": account})
>     tx2.wait(1)
>     assert fund_me.addressToAmountFunded(account.address) == 0
> ```
> 
> I'm a complete newbie in this field and thus have very limited knowledge about it.
> 
> _Thanks in advance_

Basically when I'm trying to run `fund_and_withdraw.py` in the development network, it is not finding another error :
`IndexError: list index out of range`. This is really troubling me a lot. Your help would be appreciated.

**Comment by PatrickAlphaC** [comment]
Could you please post here: https://github.com/smartcontractkit/full-blockchain-solidity-course-py

Thank you!
