### ISSUE TITLE
Brownie not detecting Ganache

### ISSUE THREAD

**Issue by WOODWEIRD** [PatrickAlphaC/brownie_fund_me#28]
5:37:00ish
brownie didn't detect ganache when deploying. but after changing the  PORT NUMBER to 8545 and the NETWORK ID to 1337 in ganache settings, it worked.
thought i'd share this error.

**Comment by PatrickAlphaC** [comment]
Thanks for sharing!! 
Closing the issue for now. Hope someone else can come across this.

**Comment by sujaykhandekar** [comment]
> 5:37:00ish brownie didn't detect ganache when deploying. but after changing the PORT NUMBER to 8545 and the NETWORK ID to 1337 in ganache settings, it worked. thought i'd share this error.

Same happened with me
