### ISSUE TITLE
ImportError: cannot import name 'deploy_mocks' from 'scripts.helpful_scripts'

### ISSUE THREAD

**Issue by mattsegura** [PatrickAlphaC/brownie_fund_me#33]
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/61678138/154335297-37752d95-6ee0-47c1-96ad-5eee6cf891ce.png">

**Comment by PatrickAlphaC** [comment]
Please make this issue in the larger repo, thanks! 

https://github.com/smartcontractkit/full-blockchain-solidity-course-py

**Comment by mattsegura** [comment]
> Please make this issue in the larger repo, thanks!
> 
> https://github.com/smartcontractkit/full-blockchain-solidity-course-py

thanks, found the issue though it was because I didn't import MockV3Aggregator in helpful_scripts
