### ISSUE TITLE
2500000 - Entrance fee; expected: 25000000000000000

### ISSUE THREAD

**Issue by ArnoldTingSu** [PatrickAlphaC/brownie_fund_me#34]
Video Timestamp: https://youtu.be/M576WGiDBdQ?t=20714

Running the script of 'fund_and_withdraw.py' gave an output of 2500000, when the expected output by Patrick was 25000000000000000 in the video.

**Comment by PatrickAlphaC** [comment]
Could you make this issue here? https://github.com/smartcontractkit/full-blockchain-solidity-course-py

Thanks!

**Comment by ArnoldTingSu** [comment]
Will do, Ty for the reply
