### ISSUE TITLE
error while trying to run with ganache-local network

### ISSUE THREAD

**Issue by Fico79** [PatrickAlphaC/brownie_fund_me#37]
![Screenshot (11)](https://user-images.githubusercontent.com/101263830/157446188-29df0105-56d3-4710-bf2d-b5c246393f29.png)
i got this error while running on the ganache-local network

**Comment by PatrickAlphaC** [comment]
Can you please make this question on the main repo? Thanks! 

https://github.com/smartcontractkit/full-blockchain-solidity-course-py
