### ISSUE TITLE
deploy on mainnet-fork

### ISSUE THREAD

**Issue by mostafaevil09** [PatrickAlphaC/brownie_fund_me#39]
**HI**
i have successfully added mainnet-fork-dev by an alchemyapi app with this code in terminal:

`brownie networks add development mainnet-fork-dev cmd=ganache-cli host=http://127.0.0.1 fork=https://eth-mainnet.alchemyapi.io/v2/QRAkGZCSGKYx-n2HNjpAys6qa5BugcV9 accounts=10 mnemonic=brownie port=8545`

however when i try to deploy on mainnet-fork-dev with this code in terminal:

`brownie run scripts/deploy.py --network mainnet-fork-dev`

i dont get any thing! no Error no nothing, its looks like it cant even finish the deploy all i get is this:

_Brownie v1.16.4 - Python development framework for Ethereum

BrownieFundMeProject is the active project.

Launching 'ganache-cli.cmd --accounts 10 --fork https://eth-mainnet.alchemyapi.io/v2/QRAkGZCSGKYx-n2HNjpAys6qa5BugcV9 --mnemonic brownie --port 8545 --hardfork istanbul'...
_
and i cant do anything else until i trash the teminal and start a new one!
any thoughts?!

**Comment by PatrickAlphaC** [comment]
Hi, please do not share your alchemy API key with the internet! Others may run up your alchemy bill!

Could you please make this an issue on the main repo? Thank you!

https://github.com/smartcontractkit/full-blockchain-solidity-course-py
