### ISSUE TITLE
Lesson 6 MockV3Aggregato Error

### ISSUE THREAD

**Issue by AlfonsoJohn** [PatrickAlphaC/brownie_fund_me#5]
<img width="1188" alt="Screen Shot 2021-11-22 at 12 37 36 AM" src="https://user-images.githubusercontent.com/67883631/142806534-dd79e143-5694-4d6e-8da7-a904347007aa.png">

**Comment by AlfonsoJohn** [comment]
Not really sure what the issue is

**Comment by PatrickAlphaC** [comment]
Do you have `MockV3Aggregator` in your `test` folder in the `contracts` folder? https://github.com/PatrickAlphaC/brownie_fund_me/blob/main/contracts/test/MockV3Aggregator.sol

**Comment by PatrickAlphaC** [comment]
You need to have it in the `contracts` folder, not the `build/contracts` folder

**Comment by AlfonsoJohn** [comment]
Oh okay, thank you so much for everything!
Cordially,
Alfonso John
