### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by vanilingys99** [PatrickAlphaC/brownie_fund_me#52]
Here it my deploy.py file : ![image](https://user-images.githubusercontent.com/92088034/192150613-f6d332d6-ba35-4c95-a852-da6637129374.png)
helpful_scripts.py file : ![image](https://user-images.githubusercontent.com/92088034/192150663-6052b22c-f81f-484b-9e70-39aa77b56c73.png)
brownie-config.yaml : ![image](https://user-images.githubusercontent.com/92088034/192150695-d94e7be1-c19f-4d21-9125-e26d0852f7fd.png)
And the problem here - ![image](https://user-images.githubusercontent.com/92088034/192150756-8e517904-0260-4097-814e-3e419f338f8c.png)

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-py
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
