### ISSUE TITLE
ValueError: sender doesn't have enough funds to send tx. The upfront cost is: 9475020000000000 and the sender's account only has: 0

### ISSUE THREAD

**Issue by Kam0teQ** [PatrickAlphaC/brownie_fund_me#54]
Hi, can anyone help me, I'm stuck in this part of Deploying the Contract FundMe. I have followed every steps but I can't seem to figure why I'm still getting this insufficient funds error....
<img width="1288" alt="Screen Shot 2022-11-24 at 1 44 59 PM" src="https://user-images.githubusercontent.com/112837124/203866991-5574a030-7495-4f3d-99b2-f2e38824d74e.png">
<img width="1288" alt="Screen Shot 2022-11-24 at 1 48 48 PM" src="https://user-images.githubusercontent.com/112837124/203867123-a126e6a8-cad9-4e03-98a3-fb7b8b4bd6bd.png">
Any ideas? Thank you...

**Comment by Kam0teQ** [comment]
<img width="1292" alt="Screen Shot 2022-11-24 at 1 50 45 PM" src="https://user-images.githubusercontent.com/112837124/203867371-3b0b6bc6-8ce7-455a-a652-fb61b430121d.png">

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-py
