### ISSUE TITLE
Issue With fund_and_withdraw.py Script

### ISSUE THREAD

**Issue by xosemanolo** [PatrickAlphaC/brownie_fund_me#7]
** GREAT tutorial thus far !!!**

The issue seems to be centered around the getEntranceFee function and I can not figure out what the issue is. Any assistance would be greatly appreciated. 

Code
https://github.com/xosemanolo/brownie_fund_me

1. brownie run scripts/deploy.py --network ganache-local 

> works well with following message:

> Brownie v1.17.1 - Python development framework for Ethereum

        BrownieFundMeProject is the active project.
        
        Running 'scripts/deploy.py::main'...
        The Active Network is ganache-local
        Deploying Mocks...
        Mock Deployed!
        price feed address
        0x1f35e1a93F5bA09A21D1de57C17957404D3f427B
        Transaction sent: 0xb32c2a81f5a1547a2031afea6b82e82873050062a59a45b9c50c4d4c6928453b
          Gas price: 20.0 gwei   Gas limit: 424483   Nonce: 9
          FundMe.constructor confirmed   Block: 10   Gas used: 385894 (90.91%)
          FundMe deployed at: 0xf62EFFb0E950177b281C2D883b820050B343a81e
        
Contract deployed to 0xf62EFFb0E950177b281C2D883b820050B343a81e

2. brownie run scripts/fund_and_withdraw.py --network ganache-local

> running into an issue with following message:

Brownie v1.17.1 - Python development framework for Ethereum

BrownieFundMeProject is the active project.

      Running 'scripts/fund_and_withdraw.py::main'...
      0xf62EFFb0E950177b281C2D883b820050B343a81e
      0x4e0826D612afCe0868b7025aA975C304c27A54Aa
        File "brownie/_cli/run.py", line 50, in main
          return_value, frame = run(
        File "brownie/project/scripts.py", line 103, in run
          return_value = f_locals[method_name](*args, **kwargs)
        File "./scripts/fund_and_withdraw.py", line 15, in main
          fund()
        File "./scripts/fund_and_withdraw.py", line 10, in fund
          entrance_fee = fund_me.getEntranceFee()
        File "brownie/network/multicall.py", line 115, in _proxy_call
          result = ContractCall.__call__(*args, **kwargs)  # type: ignore
        File "brownie/network/contract.py", line 1661, in __call__
          return self.call(*args, block_identifier=block_identifier)
        File "brownie/network/contract.py", line 1457, in call
          raise VirtualMachineError(e) from None
        File "brownie/exceptions.py", line 121, in __init__
          raise ValueError(str(exc)) from None
      ValueError: execution reverted: VM Exception while processing transaction: revert

**Comment by xosemanolo** [comment]
i figured out what the issue was

**Comment by FiroshV** [comment]
@xosemanolo , I am facing this same issue. Please explain how you resolved this.

**Comment by SGTL8** [comment]
What did you do to solve?

**Comment by etsea117** [comment]
@xosemanolo can you share your solution?
