### ISSUE TITLE
brownie.exceptions.VirtualMachineError: revert in test_fund_me.py

### ISSUE THREAD

**Issue by yrraadi-io** [PatrickAlphaC/brownie_fund_me#9]
I'm experiencing the above error even though I have added the code to handle the occurrence of such an error.

```
from scripts.helpful_scripts import get_account, LOCAL_BLOCKCHAIN_ENVIRONMENTS
from scripts.deploy import deploy_fund_me
from brownie import network, accounts, exceptions
import pytest


def test_can_fund_and_withdraw():
    account = get_account()
    fund_me = deploy_fund_me()
    entrance_fee = fund_me.getEntranceFee() + 100
    tx = fund_me.fund({"from": account, "value": entrance_fee})
    tx.wait(1)
    assert fund_me.addressToAmountFunded(account.address) == entrance_fee
    tx2 = fund_me.withdraw({"from": account})
    tx2.wait(1)
    assert fund_me.addressToAmountFunded(account.address) == 0


def test_only_owner_can_witdraw():
    if network.show_active() not in LOCAL_BLOCKCHAIN_ENVIRONMENTS:
        pytest.skip("only for local testing")
    fund_me = deploy_fund_me()
    bad_actor = accounts.add()
    with pytest.raises(exceptions.VirtualMachineError):
        fund_me.withdraw({"from": bad_actor})
```

> Error:
> FAILED tests/test_fund_me.py::test_can_fund_and_withdraw - brownie.exceptions.VirtualMachineError: revert

Would appreciate any advice on how I can fix this.

**Comment by yrraadi-io** [comment]
I closed the terminal and re-ran it and it worked...not sure what the issue was initially.

**Comment by PatrickAlphaC** [comment]
Glad it's working now!

**Comment by wankin168** [comment]
Hi, 

I am encountering the same issue when I run "brownie test --network mainnet-fork-dev". 

The error occur in line "entrance_fee = fund_me.getEntranceFee()  + 100" and the error message is the same: "FAILED tests/test_fund_me.py::test_can_fund_and_withdraw - brownie.exceptions.VirtualMachineError: revert".  

I tried to re-run the terminal but the error still here. I have no idea how to solve it, could anyone please help? Thank you.

**Comment by PatrickAlphaC** [comment]
Could you make this a stackoverflow question wankin?
